name: Sync to Overleaf

on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Push to Overleaf
        env:
          OVERLEAF_PROJECT_ID: 6aa85ea19dc65d7c192e92fe
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
        run: |
          if [ -z "$OVERLEAF_EMAIL" ] || [ -z "$OVERLEAF_PASSWORD" ]; then
            echo "Error: OVERLEAF_EMAIL or OVERLEAF_PASSWORD secrets are not set."
            exit 1
          fi
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Overleaf requiere que el usuario sea literalmente 'git' y la contraseña sea el Token.
          git remote add overleaf "https://git:${OVERLEAF_PASSWORD}@git.overleaf.com/${OVERLEAF_PROJECT_ID}"
          
          # Overleaf suele rechazar los 'git push --force'.
          # Traemos la historia de Overleaf y la fusionamos forzando que la versión de GitHub gane (-s ours)
          # para evitar conflictos con el main.tex por defecto de Overleaf.
          git fetch overleaf main
          git merge overleaf/main -s ours --allow-unrelated-histories --no-edit
          
          # Hacemos push normal a la rama main de overleaf
          GIT_CURL_VERBOSE=1 GIT_TRACE=1 git push overleaf HEAD:main
