name: Sync to Overleaf

on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Push to Overleaf
        env:
          OVERLEAF_PROJECT_ID: 6182249883cfqncwryrctv
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
        run: |
          if [ -z "$OVERLEAF_EMAIL" ] || [ -z "$OVERLEAF_PASSWORD" ]; then
            echo "Error: OVERLEAF_EMAIL or OVERLEAF_PASSWORD secrets are not set."
            exit 1
          fi
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Utilizamos printf para evitar saltos de línea y jq -sRr para encodear
          ENCODED_EMAIL=$(printf "%s" "$OVERLEAF_EMAIL" | jq -sRr '@uri')
          ENCODED_PASSWORD=$(printf "%s" "$OVERLEAF_PASSWORD" | jq -sRr '@uri')
          git remote add overleaf "https://${ENCODED_EMAIL}:${ENCODED_PASSWORD}@git.overleaf.com/${OVERLEAF_PROJECT_ID}"
          # Hacemos push a la rama master de overleaf, habilitando trazas de debug
          GIT_CURL_VERBOSE=1 GIT_TRACE=1 git push overleaf HEAD:master --force
